Add safeguard.

diff --git a/.github/workflows/build-release.yml b/.github/workflows/build-release.yml
--- a/.github/workflows/build-release.yml
+++ b/.github/workflows/build-release.yml
@@ -20,6 +20,14 @@ jobs:
     runs-on: ubuntu-latest
     needs: version
     steps:
+      - name: Check version format
+        run: |
+          if [[ "${{ needs.version.outputs.version }}" != *"-SNAPSHOT"* ]]; then
+            echo "Release version is correct (does not contain -SNAPSHOT)"
+          else
+            echo "::error::Release version should not contain -SNAPSHOT"
+            exit 1
+          fi
       - name: Checkout code
         uses: actions/checkout@v4
       - name: Set up JDK
@@ -34,9 +42,7 @@ jobs:
           git config user.email "actions@github.com"
       - name: Set release version
         run: |
-          mvn versions:set -DremoveSnapshot
-          git add .
-          git commit -m "chore: prepare for release ${{ needs.version.outputs.version }}"
+          mvn versions:set versions:commit -DremoveSnapshot
 #
 #      - name: Configure Git
 #        run: |
