update build

diff --git a/.github/workflows/create-release.yml b/.github/workflows/create-release.yml
--- a/.github/workflows/create-release.yml
+++ b/.github/workflows/create-release.yml
@@ -8,7 +8,49 @@ permissions:
 
 jobs:
   release:
-    uses: ./.github/workflows/_release-version.yml
+    runs-on: ubuntu-latest
+    outputs:
+      version: ${{ steps.set_version.outputs.tag_version }}
+    steps:
+      - name: Check version format
+        run: |
+          CURRENT_SNAPSHOT=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
+          if [[ "${CURRENT_SNAPSHOT}" != *"-SNAPSHOT"* ]]; then
+            echo "Release version is correct (does not contain -SNAPSHOT)"
+          else
+            echo "::error::Release version should not contain -SNAPSHOT"
+            exit 1
+          fi
+      - name: Checkout code
+        uses: actions/checkout@v4
+      - name: Set up JDK
+        uses: actions/setup-java@v4
+        with:
+          distribution: 'corretto'
+          java-version: '24'
+          architecture: x64
+      - name: Configure Git
+        run: |
+          git config user.name "GitHub Actions"
+          git config user.email "gjong@users.noreply.github.com"
+      - name: Set release version
+        id: set_version
+        run: |
+          mvn versions:set versions:commit -DremoveSnapshot -q
+          RELEASE_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
+          echo "Building release for: ${RELEASE_VERSION}"
+          echo "RELEASE_VERSION=${RELEASE_VERSION}" >> $GITHUB_ENV
+          echo "tag_version=${RELEASE_VERSION}" >> $GITHUB_OUTPUT
+      - name: Commit release
+        run: |
+          git add .
+          git commit -m "chore: prepare release ${{ env.RELEASE_VERSION }}"
+          git push
+      - name: Tagging stable release
+        run: |
+          git tag ${{ env.RELEASE_VERSION }}
+          git push origin ${{ env.RELEASE_VERSION }}
+
   github-release:
     needs: release
     runs-on: ubuntu-latest
@@ -24,6 +66,32 @@ jobs:
           generate_release_notes: true
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+
   prepare-next:
     needs: release
-    uses: ./.github/workflows/_prepare-snapshot.yml
+    runs-on: ubuntu-latest
+    if: ${{ needs.release.outputs.version }}
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v4
+      - name: Set up JDK
+        uses: actions/setup-java@v4
+        with:
+          distribution: 'corretto'
+          java-version: '24'
+          architecture: x64
+      - name: Configure Git
+        run: |
+          git config user.name "GitHub Actions"
+          git config user.email "gjong@users.noreply.github.com"
+          git pull
+      - name: Prepare next build phase
+        run: |
+          mvn versions:set versions:commit -DnextSnapshot -q
+          NEXT_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
+          echo "NEXT_VERSION=${NEXT_VERSION}" >> $GITHUB_ENV
+      - name: Pushing committed snapshot
+        run: |
+          git add .
+          git commit -m "chore: prepare snapshot version ${{ env.NEXT_VERSION }}"
+          git push
